import 'package:flutter/material.dart';

const skillColors = {
  'Green': Colors.green,
  'Blue': Colors.blue,
  'Red': Colors.red,
  'Yellow': Colors.yellow,
  'Orange': Colors.orange,
  'Purple': Colors.purple,
  'Pink': Colors.pink,
  'Cyan': Colors.cyan,
  'Teal': Colors.teal,
  'Amber': Colors.amber,
  'Deep Orange': Colors.deepOrange,
  'Deep Purple': Colors.deepPurple,
  'Indigo': Colors.indigo,
  'Light Blue': Colors.lightBlue,
  'Light Green': Colors.lightGreen,
  'Lime': Colors.lime,
  'Brown': Colors.brown,
  'Grey': Colors.grey,
  'Blue Grey': Colors.blueGrey,
};

const appColors = {
  'Green': Colors.green,
  'Blue': Colors.blue,
  'Red': Colors.red,
  'Yellow': Colors.yellow,
  'Orange': Colors.orange,
  'Purple': Colors.purple,
  'Pink': Colors.pink,
  'Brown': Colors.brown,
};

Map<String, IconData> appIcons = {
  'Running': Icons.directions_run,
  'Biking': Icons.directions_bike,
  'Walking': Icons.directions_walk,
  'Soccer': Icons.sports_soccer,
  'Basketball': Icons.sports_basketball,
  'Tennis': Icons.sports_tennis,
  'Volleyball': Icons.sports_volleyball,
  'Golf': Icons.sports_golf,
  'Baseball': Icons.sports_baseball,
  'Hockey': Icons.sports_hockey,
  'Swimming': Icons.pool,
  'Airplane': Icons.airplanemode_active,
  'Takeoff': Icons.flight_takeoff,
  'Landing': Icons.flight_land,
  'Airport': Icons.local_airport,
  'Train': Icons.train,
  'Car': Icons.directions_car,
  'Bus': Icons.directions_bus,
  'Boat': Icons.directions_boat,
  'Ferry': Icons.directions_ferry,
  'Subway': Icons.directions_subway,
  'Tram': Icons.tram,
  'Hiking': Icons.hiking,
  'Activity': Icons.local_activity,
  'Movies': Icons.local_movies,
  'Play': Icons.local_play,
  'Convenience': Icons.local_convenience_store,
  'Grocery': Icons.local_grocery_store,
  'Restaurant': Icons.restaurant,
  'Cafe': Icons.local_cafe,
  'Bar': Icons.local_bar,
  'Dining': Icons.local_dining,
  'Pizza': Icons.local_pizza,
  'Drink': Icons.local_drink,
  'Laundry': Icons.local_laundry_service,
  'Car Wash': Icons.local_car_wash,
  'Pharmacy': Icons.local_pharmacy,
  'Hospital': Icons.local_hospital,
  'Hotel': Icons.local_hotel,
  'Taxi': Icons.local_taxi,
  'ATM': Icons.local_atm,
  'Florist': Icons.local_florist,
  'Mall': Icons.local_mall,
  'Sightseeing': Icons.local_see,
  'Parking': Icons.local_parking,
  'Post Office': Icons.local_post_office,
  'Printshop': Icons.local_printshop,
  'Shipping': Icons.local_shipping,
  'Gas Station': Icons.local_gas_station,
  'Alarm': Icons.access_alarm,
  'Time': Icons.access_time,
  'Bell': Icons.alarm,
  'Later': Icons.watch_later,
  'Timer': Icons.timer,
  'Timer Off': Icons.timer_off,
  'Schedule': Icons.schedule,
  'Today': Icons.today,
  'Update': Icons.update,
  'Hourglass Empty': Icons.hourglass_empty,
  'Hourglass Full': Icons.hourglass_full,
  'Event': Icons.event,
  'Event Avail.': Icons.event_available,
  'Event Busy': Icons.event_busy,
  'Event Note': Icons.event_note,
  'Event Seat': Icons.event_seat,
  'Notifications': Icons.notifications,
  'Notif. Active': Icons.notifications_active,
  'Notif. None': Icons.notifications_none,
  'Notif. Off': Icons.notifications_off,
  'Notif. Paused': Icons.notifications_paused,
  'Directions': Icons.directions,
  'Dir. Railway': Icons.directions_railway,
  'Dir. Transit': Icons.directions_transit,
  'Money': Icons.attach_money,
  'Money Off': Icons.money_off,
  'Payment': Icons.payment,
  'Credit Card': Icons.credit_card,
  'Debit Card': Icons.credit_card_outlined,
  'Acct. Balance': Icons.account_balance,
  'Acct. Wallet': Icons.account_balance_wallet,
  'Acct. Box': Icons.account_box,
  'Acct. Circle': Icons.account_circle,
  'Acct. Tree': Icons.account_tree,
  'Assignment': Icons.assignment,
  'Assmt. Late': Icons.assignment_late,
  'Assmt. Return': Icons.assignment_return,
  'Assmt. Retd.': Icons.assignment_returned,
  'Assmt. Turned In': Icons.assignment_turned_in,
  'Feedback': Icons.feedback,
  'Ques. Answer': Icons.question_answer,
  'Chat': Icons.chat,
  'Mail': Icons.mail,
  'Email': Icons.email,
  'Phone': Icons.phone,
  'Smartphone': Icons.smartphone,
  'Phone Android': Icons.phone_android,
  'Phone iPhone': Icons.phone_iphone,
  'Desktop': Icons.desktop_windows,
  'Laptop': Icons.laptop,
  'Tablet': Icons.tablet,
  'Watch': Icons.watch,
  'TV': Icons.tv,
  'Game Console': Icons.videogame_asset,
  'Headset': Icons.headset,
  'Mic': Icons.mic,
  'Mic Off': Icons.mic_off,
  'Camera': Icons.camera,
  'Photo': Icons.photo,
  'Video': Icons.video_call,
  'Video Off': Icons.videocam_off,
  'Settings': Icons.settings,
  'Settings Bright.': Icons.settings_brightness,
  'Settings Input': Icons.settings_input_component,
  'Settings BT': Icons.settings_bluetooth,
  'Settings Eth.': Icons.settings_ethernet,
  'Settings Phone': Icons.settings_phone,
  'Settings Voice': Icons.settings_voice,
  'Settings Apps': Icons.settings_applications,
  'Settings Backup': Icons.settings_backup_restore,
  'Settings Security': Icons.settings_system_daydream,
  'Settings Display': Icons.settings_display,
  'Settings Power': Icons.settings_power,
  'Settings Remote': Icons.settings_remote,
  'Settings Access.': Icons.settings_accessibility,
  'Settings Access. 2T': Icons.settings_accessibility_outlined,
  'Settings Apps 2T': Icons.settings_applications_outlined,
  'Settings Backup': Icons.settings_backup_restore,
  'Settings BT 2T': Icons.settings_bluetooth_outlined,
  'Settings Cell': Icons.settings_cell,
  'Settings Cell 2T': Icons.settings_cell_outlined,
  'Settings Eth. 2T': Icons.settings_ethernet_outlined,
  'Settings Inp. Ant.': Icons.settings_input_antenna,
  'Settings Inp. Ant. 2T': Icons.settings_input_antenna_outlined,
  'Settings Inp. Comp.': Icons.settings_input_component,
  'Settings Inp. Comp. 2T': Icons.settings_input_component_outlined,
  'Settings Inp. Comp. 2T': Icons.settings_input_composite,
  'Settings Inp. Comp. 2T': Icons.settings_input_composite_outlined,
  'Settings Inp. HDMI': Icons.settings_input_hdmi,
  'Settings Inp. HDMI 2T': Icons.settings_input_hdmi_outlined,
  'Settings Inp. SVideo': Icons.settings_input_svideo,
  'Settings Inp. SVideo 2T': Icons.settings_input_svideo_outlined,
  'Settings Onewheel': Icons.settings_overscan,
  'Settings Onewheel 2T': Icons.settings_overscan_outlined,
  'Settings Phone 2T': Icons.settings_phone_outlined,
  'Settings Power 2T': Icons.settings_power_outlined,
  'Settings Remote 2T': Icons.settings_remote_outlined,
  'Backup': Icons.backup,
  'Backup Table': Icons.backup_table,
  'Build': Icons.build,
  'Cast': Icons.cast,
  'Cast Connected': Icons.cast_connected,
  'Computer': Icons.computer,
  'Desktop Mac': Icons.desktop_mac,
  'Desktop Win.': Icons.desktop_windows,
  'Dev. Board': Icons.developer_board,
  'Device Hub': Icons.device_hub,
  'Device Unk.': Icons.device_unknown,
  'Devices': Icons.devices,
  'Dock': Icons.dock,
  'Gamepad': Icons.gamepad,
  'Headset Mic': Icons.headset_mic,
  'Headset Off': Icons.headset_off,
  'Keyboard': Icons.keyboard,
  'Kbd Arrow Down': Icons.keyboard_arrow_down,
  'Kbd Arrow Left': Icons.keyboard_arrow_left,
  'Kbd Arrow Right': Icons.keyboard_arrow_right,
  'Kbd Arrow Up': Icons.keyboard_arrow_up,
  'Kbd Backspace': Icons.keyboard_backspace,
  'Kbd Capslock': Icons.keyboard_capslock,
  'Kbd Hide': Icons.keyboard_hide,
  'Kbd Return': Icons.keyboard_return,
  'Kbd Tab': Icons.keyboard_tab,
  'Kbd Voice': Icons.keyboard_voice,
  'Laptop Chrome': Icons.laptop_chromebook,
  'Laptop Mac': Icons.laptop_mac,
  'Laptop Win.': Icons.laptop_windows,
  'Memory': Icons.memory,
  'Mouse': Icons.mouse,
  'Phone iPhone': Icons.phone_iphone,
  'Phonelink': Icons.phonelink,
  'Phonelink Erase': Icons.phonelink_erase,
  'Phonelink Lock': Icons.phonelink_lock,
  'Phonelink Off': Icons.phonelink_off,
  'Phonelink Ring': Icons.phonelink_ring,
  'Phonelink Setup': Icons.phonelink_setup,
  'Power Input': Icons.power_input,
  'Router': Icons.router,
  'Scanner': Icons.scanner,
  'Security': Icons.security,
  'Sim Card': Icons.sim_card,
  'Speaker': Icons.speaker,
  'Speaker Group': Icons.speaker_group,
  'Speaker Notes': Icons.speaker_notes,
  'Speaker Notes Off': Icons.speaker_notes_off,
  'Tablet Android': Icons.tablet_android,
  'Tablet Mac': Icons.tablet_mac,
  'Toys': Icons.toys,
  'Video Game': Icons.videogame_asset,
  'Web': Icons.web,
  'Game Control': Icons.gamepad,
  'Game Cont. Off': Icons.gamepad_outlined,
  'Stream': Icons.stream,
  'Web Asset': Icons.web_asset,
  'Desktop Access': Icons.desktop_access_disabled,
  'Phone Disabled': Icons.phone_disabled,
  'TV Off': Icons.tv_off,
  'Lightbulb': Icons.lightbulb,
  'Eco': Icons.eco,
  'Filter': Icons.filter,
  'Grain': Icons.grain,
  'Layers': Icons.layers,
  'Leak Add': Icons.leak_add,
  'Leak Remove': Icons.leak_remove,
  'Mono Photos': Icons.monochrome_photos,
  'Palette': Icons.palette,
  'Panorama': Icons.panorama,
  'Panorama Hor.': Icons.panorama_horizontal,
  'Panorama Vert.': Icons.panorama_vertical,
  'Panorama Wide': Icons.panorama_wide_angle,
  'Photo Album': Icons.photo_album,
  'Photo Camera': Icons.photo_camera,
  'Photo Filter': Icons.photo_filter,
  'Photo Library': Icons.photo_library,
  'Style': Icons.style,
  'Switch Camera': Icons.switch_camera,
  'Switch Video': Icons.switch_video,
  'Add To Photos': Icons.add_to_photos,
  'Crop': Icons.crop,
  'Crop 16:9': Icons.crop_16_9,
  'Crop 3:2': Icons.crop_3_2,
  'Crop 5:4': Icons.crop_5_4,
  'Crop 7:5': Icons.crop_7_5,
  'Crop Din': Icons.crop_din,
  'Crop Free': Icons.crop_free,
  'Crop Landscape': Icons.crop_landscape,
  'Crop Original': Icons.crop_original,
  'Crop Portrait': Icons.crop_portrait,
  'Crop Rotate': Icons.crop_rotate,
  'Crop Square': Icons.crop_square,
  'Dehaze': Icons.dehaze,
  'Details': Icons.details,
  'Edit': Icons.edit,
  'Exposure': Icons.exposure,
  'Exp. Neg. 1': Icons.exposure_neg_1,
  'Exp. Neg. 2': Icons.exposure_neg_2,
  'Exp. Plus 1': Icons.exposure_plus_1,
  'Exp. Plus 2': Icons.exposure_plus_2,
  'Exp. Zero': Icons.exposure_zero,
  'Filter 1': Icons.filter_1,
  'Filter 2': Icons.filter_2,
  'Filter 3': Icons.filter_3,
  'Filter 4': Icons.filter_4,
  'Filter 5': Icons.filter_5,
  'Filter 6': Icons.filter_6,
  'Filter 7': Icons.filter_7,
  'Filter 8': Icons.filter_8,
  'Filter 9': Icons.filter_9,
  'Filter 9 Plus': Icons.filter_9_plus,
  'Filter B&W': Icons.filter_b_and_w,
  'Filter Center': Icons.filter_center_focus,
  'Filter Drama': Icons.filter_drama,
  'Filter Frames': Icons.filter_frames,
  'Filter HDR': Icons.filter_hdr,
  'Filter None': Icons.filter_none,
  'Filter Tilt': Icons.filter_tilt_shift,
  'Filter Vintage': Icons.filter_vintage,
  'Flare': Icons.flare,
  'Flash Auto': Icons.flash_auto,
  'Flash Off': Icons.flash_off,
  'Flash On': Icons.flash_on,
  'Flip': Icons.flip,
  'Gradient': Icons.gradient,
  'Grid Off': Icons.grid_off,
  'Grid On': Icons.grid_on,
  'HDR Off': Icons.hdr_off,
  'HDR On': Icons.hdr_on,
  'HDR Strong': Icons.hdr_strong,
  'HDR Weak': Icons.hdr_weak,
  'Healing': Icons.healing,
  'Image': Icons.image,
  'Img. Aspect': Icons.image_aspect_ratio,
  'Img. Search': Icons.image_search,
  'Iso': Icons.iso,
  'Landscape': Icons.landscape,
  'Lens': Icons.lens,
  'Linked Cam.': Icons.linked_camera,
  'Looks': Icons.looks,
  'Looks 3': Icons.looks_3,
  'Looks 4': Icons.looks_4,
  'Looks 5': Icons.looks_5,
  'Looks 6': Icons.looks_6,
  'Looks One': Icons.looks_one,
  'Looks Two': Icons.looks_two,
  'Loupe': Icons.loupe,
  'Movie': Icons.movie,
  'Movie Creat.': Icons.movie_creation,
  'Movie Filter': Icons.movie_filter,
  'Music Note': Icons.music_note,
  'Music Off': Icons.music_off,
  'Music Video': Icons.music_video,
  'Nature': Icons.nature,
  'Nat. People': Icons.nature_people,
  'Navigate B4': Icons.navigate_before,
  'Navigate Nx': Icons.navigate_next,
  'Photo Size': Icons.photo_size_select_actual,
  'Photo Size L': Icons.photo_size_select_large,
  'Photo Size S': Icons.photo_size_select_small,
  'Pic. As PDF': Icons.picture_as_pdf,
  'Portrait': Icons.portrait,
  'Receipt Long': Icons.receipt_long,
  'Slideshow': Icons.slideshow,
  'Straighten': Icons.straighten,
  'Tag Faces': Icons.tag_faces,
  'Texture': Icons.texture,
  'Tune': Icons.tune,
  'Vid. Call': Icons.video_call,
  'Video Label': Icons.video_label,
  'Video Lib.': Icons.video_library,
  'Video Set.': Icons.video_settings,
  'View Comfy': Icons.view_comfy,
  'View Compact': Icons.view_compact,
  'Vignette': Icons.vignette,
  'WB Auto': Icons.wb_auto,
  'WB Cloudy': Icons.wb_cloudy,
  'WB Incand.': Icons.wb_incandescent,
  'WB Irides.': Icons.wb_iridescent,
  'WB Sunny': Icons.wb_sunny,
};
